site:
  name: Bali Zen
  site: 'https://balizen.ro'
  base: '/'
  trailingSlash: ignore
  googleSiteVerificationId: tobeupdated

# Default SEO metadata
metadata:
  title:
    default: Bali Zen - Ploiesti
    template: '%s â€” Bali Zen | Ploiesti'
  description: 'Bali Zen | Ploiesti - Sanctuarul tau pentru relaxare si armonie din Ploiesti. Studioul nostru de masaj este dedicat oferirii unui refugiu linistitor, departe de agitatia vietii cotidiene.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Bali Zen | Ploiesti
    images:
      - url: '/images/balizen_50.jpg'
        width: 1200
        height: 628
    type: website

i18n:
  language: ro
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  enabled: true
  vendors:
    facebookPixel:
      id: 2269890693426339
    googleAnalytics:
      id: G-QZ8FEVGH7X # or "G-XXXXXXXXXX"
    googleTagManager:
      id: GTM-KXL82G4N # or "GTM-XXXXXXXXXX"

ui:
  theme: 'light:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
